// Finnish noun/adjective case labels — keys are Voikko-derived compact tag strings
export const FINNISH_CASE_LABELS: Record<string, string> = {
  'sg nom': 'Singular Nominative — basic subject form',
  'sg gen': 'Singular Genitive — possession, object of many postpositions',
  'sg acc': 'Singular Accusative — direct object (total)',
  'sg par': 'Singular Partitive — partial/incomplete action, negation, uncountability',
  'sg ine': 'Singular Inessive — location inside (in, inside)',
  'sg ela': 'Singular Elative — motion from inside (out of)',
  'sg ill': 'Singular Illative — motion into or onto',
  'sg ade': 'Singular Adessive — location on a surface (on, at)',
  'sg abl': 'Singular Ablative — motion from a surface (from)',
  'sg all': 'Singular Allative — motion to a surface (onto, to)',
  'sg ess': 'Singular Essive — temporary state (as, being)',
  'sg tra': 'Singular Translative — change of state (becoming, turning into)',
  'sg ins': 'Singular Instructive — manner or means (by means of)',
  'sg abe': 'Singular Abessive — without',
  'sg com': 'Singular Comitative — together with',
  'pl nom': 'Plural Nominative',
  'pl gen': 'Plural Genitive',
  'pl acc': 'Plural Accusative',
  'pl par': 'Plural Partitive',
  'pl ine': 'Plural Inessive',
  'pl ela': 'Plural Elative',
  'pl ill': 'Plural Illative',
  'pl ade': 'Plural Adessive',
  'pl abl': 'Plural Ablative',
  'pl all': 'Plural Allative',
  'pl ess': 'Plural Essive',
  'pl tra': 'Plural Translative',
  'pl ins': 'Plural Instructive',
  'pl abe': 'Plural Abessive',
  'pl com': 'Plural Comitative',
};

// Finnish verb form labels
export const FINNISH_VERB_LABELS: Record<string, string> = {
  'inf a': 'A-Infinitive — basic dictionary form (to do)',
  'inf e': 'E-Infinitive — "while doing" (in/when doing)',
  'inf ma': 'MA-Infinitive — purpose or obligation (in order to do)',
  'ps1 sg af': '1st Person Singular Affirmative — I do',
  'ps2 sg af': '2nd Person Singular Affirmative — you do',
  'ps3 sg af': '3rd Person Singular Affirmative — he/she/it does',
  'ps1 pl af': '1st Person Plural Affirmative — we do',
  'ps2 pl af': '2nd Person Plural Affirmative — you (all) do',
  'ps3 pl af': '3rd Person Plural Affirmative — they do',
  'ps1 sg neg': '1st Person Singular Negative — I do not',
  'ps2 sg neg': '2nd Person Singular Negative — you do not',
  'ps3 sg neg': '3rd Person Singular Negative — he/she/it does not',
  'ps3 sg ps af': '3rd Person Singular Active Affirmative',
  'ps pres af': 'Present Tense Affirmative',
  'ps past af': 'Past Tense (Imperfect) Affirmative',
  'ps cond af': 'Conditional Affirmative — would do',
  'ps impr af': 'Imperative Affirmative — do!',
  'ps potn af': 'Potential Affirmative — might do',
  'pp pres': 'Present Passive',
  'pp past': 'Past Passive',
  'pp cond': 'Conditional Passive',
  'pp impr': 'Imperative Passive',
  'pcp1 af': 'Present Active Participle — doing',
  'pcp2 af': 'Past Active Participle — having done',
  'pcp1 pp': 'Present Passive Participle — being done',
  'pcp2 pp': 'Past Passive Participle — having been done',
  'pcp agent': 'Agent Participle — done by (someone)',
  'pcp neg': 'Negative Participle — without doing',
};

// Estonian noun/adjective case labels — keys match Vabamorf form tags
export const ESTONIAN_CASE_LABELS: Record<string, string> = {
  'sg n': 'Singular Nominative — basic form, subject',
  'sg g': 'Singular Genitive — possession, attribute, object',
  'sg p': 'Singular Partitive — partial quantity, negation',
  'sg ill': 'Singular Illative — motion into',
  'sg in': 'Singular Inessive — location inside (in)',
  'sg el': 'Singular Elative — motion from inside (from)',
  'sg all': 'Singular Allative — motion toward (to)',
  'sg ad': 'Singular Adessive — location at or on',
  'sg abl': 'Singular Ablative — motion away from (from)',
  'sg tr': 'Singular Translative — change into (into, as)',
  'sg term': 'Singular Terminative — up to, until',
  'sg es': 'Singular Essive — in the capacity of (as)',
  'sg ab': 'Singular Abessive — without',
  'sg kom': 'Singular Comitative — together with',
  'pl n': 'Plural Nominative',
  'pl g': 'Plural Genitive',
  'pl p': 'Plural Partitive',
  'pl ill': 'Plural Illative',
  'pl in': 'Plural Inessive',
  'pl el': 'Plural Elative',
  'pl all': 'Plural Allative',
  'pl ad': 'Plural Adessive',
  'pl abl': 'Plural Ablative',
  'pl tr': 'Plural Translative',
  'pl term': 'Plural Terminative',
  'pl es': 'Plural Essive',
  'pl ab': 'Plural Abessive',
  'pl kom': 'Plural Comitative',
};

// Estonian verb form labels
export const ESTONIAN_VERB_LABELS: Record<string, string> = {
  'da': 'Da-Infinitive — basic dictionary form (to do)',
  'ma': 'Ma-Infinitive — purpose infinitive (in order to do)',
  'ps1 sg af': '1st Person Singular Affirmative — I do',
  'ps2 sg af': '2nd Person Singular Affirmative — you do',
  'ps3 sg af': '3rd Person Singular Affirmative — he/she/it does',
  'ps1 pl af': '1st Person Plural Affirmative — we do',
  'ps2 pl af': '2nd Person Plural Affirmative — you (all) do',
  'ps3 pl af': '3rd Person Plural Affirmative — they do',
  'ps1 sg neg': '1st Person Singular Negative',
  'ps2 sg neg': '2nd Person Singular Negative',
  'ps3 sg neg': '3rd Person Singular Negative',
  'ps past': 'Personal Past Tense (Imperfect)',
  'impers pres af': 'Impersonal Present Affirmative',
  'impers past af': 'Impersonal Past Affirmative',
  'impers pres neg': 'Impersonal Present Negative',
  'impers past neg': 'Impersonal Past Negative',
  'cond af': 'Conditional Affirmative — would do',
  'cond neg': 'Conditional Negative',
  'quot': 'Quotative — reportedly does',
  'imprt sg af': 'Imperative Singular Affirmative — do!',
  'imprt pl af': 'Imperative Plural Affirmative — do! (plural)',
  'imprt sg neg': 'Imperative Singular Negative — do not!',
  'ger': 'Gerund — the act of doing',
  'sup ill': 'Supine Illative (ma-form, destination)',
  'sup in': 'Supine Inessive (mas-form, ongoing)',
  'sup el': 'Supine Elative (mast-form, finished)',
  'sup abl': 'Supine Ablative (malt-form)',
  'sup tr': 'Supine Translative (maks-form, purpose)',
  'partic pres af': 'Present Active Participle — doing',
  'partic past af': 'Past Active Participle — having done',
  'partic pres neg': 'Present Negative Participle — not doing',
  'partic past neg': 'Past Negative Participle',
};

export function getMorphLabel(form: string, language: 'fi' | 'et'): string {
  if (language === 'fi') {
    return FINNISH_CASE_LABELS[form] ?? FINNISH_VERB_LABELS[form] ?? form;
  }
  return ESTONIAN_CASE_LABELS[form] ?? ESTONIAN_VERB_LABELS[form] ?? form;
}
